### ISSUE TITLE
Explain what outputs are needed out of band

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/notification-terraform#10]
Some information that is extracted from the infrastructure after deployment for the following:

- ACM validation
- SES validation
- Target group allocation

Explain how these are used and write a command that will extract them for you and where they need to be applied in what way.

**Comment by AntoineAugusti** [comment]
This is a documentation task mainly, but it would be good to have a script, maybe with the AWS CLI? Not something rock solid.

**Comment by AntoineAugusti** [comment]
Manual actions we had to do for our infrastructure:

- For [ACM](https://github.com/cds-snc/notification-terraform/blob/main/aws/dns/acm.tf) we do not automatically set the required DNS records to have a valid certificate because the DNS zone is managed on a different account. We had to copy/paste CNAME records to https://github.com/cds-snc/dns/blob/master/terraform/notification.canada.ca-zone.tf 
- For [SES](https://github.com/cds-snc/notification-terraform/blob/main/aws/dns/ses.tf) this is similar. We had to add DNS records for TXT and DKIM validation on the DNS repo as well (Terraform objects `aws_ses_domain_identity` et `aws_ses_domain_dkim`)
- For [load balancer target groups](https://github.com/cds-snc/notification-terraform/blob/main/aws/eks/alb.tf), we need to put the ARNs on target group files for our Kubernetes cluster in staging [and production](https://github.com/cds-snc/notification-manifests/tree/main/env/production) (Terraform object aws_alb_target_group)
- In order to use [AWS Shield Advanced](https://aws.amazon.com/shield/) we had to click on a button to accept a monthly 3k USD bill/account
- We had to request limits for SES, SNS
- We had to order Pinpoint long code numbers
- We had to extract IAM credentials from the Terraform state in DynamoDB to get AWS keys

The idea would be to keep this list in a Markdown file. Maybe the README is enough, maybe we can put that in another file! A complete list is what's most important but if we can get all these values from the AWS CLI that would be nice. Otherwise, the last resort is taking some values from the AWS Console on the web UI.

**Comment by AntoineAugusti** [comment]
Fixed by #125
